export const HotelList = [
  {
    id: 1,
    name: "The Gate Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/sFhsJdD/hotel1.jpg",
  },
  {
    id: 2,
    name: "Spring Lagoon Motel",
    country: "GB",
    stars: 5,
    price: 40,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "200",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/XVBdt1d/hotel2.jpg",
  },
  {
    id: 3,
    name: "Serene Isle Hotel",
    country: "US",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/ZfQgjCW/hotel3.jpg",
  },
  {
    id: 4,
    name: "Majestic Crow Hotel & Spa",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/4rf6yd5/hotel4.jpg",
  },
  {
    id: 5,
    name: "Jade Castle Resort & Spa",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/dBL0VHP/hotel5.jpg",
  },
  {
    id: 6,
    name: "Liberty Resort & Spa",
    country: "US",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/xS4tX0j/hotel6.jpg",
  },
  {
    id: 7,
    name: "Deluxe Motel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/hcFJPNf/hotel7.jpg",
  },
  {
    id: 8,
    name: "Winter Nimbus Hotel & Spa",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/Z1y9vZp/hotel8.jpg",
  },
  {
    id: 9,
    name: "Silver Castle Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/YQZtqpN/hotel9.jpg",
  },
  {
    id: 10,
    name: "Malachite Thicket Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/9wdnQS3/hotel10.jpg",
  },
  {
    id: 11,
    name: "Marina Dune Hotel ",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/NV48rcp/hotel11.jpg",
  },
  {
    id: 12,
    name: "Deluxe Motel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/9r1r631/hotel12.jpg",
  },
  {
    id: 13,
    name: "Emerald Resort",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/jrsXW1j/hotel13.jpg",
  },
  {
    id: 14,
    name: "Mahogany Resort & Spa",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/pZ379zx/hotel14.jpg",
  },
  {
    id: 15,
    name: "Seven Seas Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/JvZ4jqW/hotel15.jpg",
  },
  {
    id: 16,
    name: "Ruby Seaside Resort",
    country: "GB",
    stars: 4,
    price: 35,
    wifi: true,
    breakfest: "Free",
    view: "Sea",
    bedrooms: 3,
    size: "175",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/jgDww6P/hotel16.jpg",
  },
  {
    id: 17,
    name: "King's Shack Motel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "Beach",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/87w6GLB/hotel17.jpg",
  },
  {
    id: 18,
    name: "Remote Pass Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/HNzKQX1/hotel18.jpg",
  },
  {
    id: 19,
    name: "Triple Bazaar Hotel",
    country: "GB",
    stars: 4,
    price: 30,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 5,
    size: "150",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/q1MGMGv/hotel19.jpg",
  },
  {
    id: 20,
    name: "Voyage Hotel",
    country: "GB",
    stars: 3,
    price: 15,
    wifi: true,
    breakfest: "Free",
    view: "City",
    bedrooms: 7,
    size: "120",
    details:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce quis quam et lacus finibus volutpat. Donec ac pharetra enim, ut luctus dui. Ut vel tortor a risus accumsan facilisis. Sed ultricies varius dapibus. In hac habitasse platea dictumst. In id nisi placerat, dapibus ante eget, feugiat nunc. Pellentesque rhoncus faucibus pretium. Phasellus id sollicitudin dolor. Maecenas porttitor dictum consectetur. Aliquam rutrum ex id massa dictum vestibulum. Donec sit amet neque ac ligula egestas semper quis ac lacus. Fusce ullamcorper, dolor ac tincidunt tempor, nisi nunc semper libero, at egestas lacus nisi ut felis. Etiam eget odio suscipit, posuere nisi non, aliquam augue. Aliquam metus purus, sagittis in ipsum non, placerat viverra risus.",
    available: true,
    image: "https://i.ibb.co/q1MGMGv/hotel19.jpg",
  },
];
